language: node_js

node_js:
  - 9
  - lts/*

before_install:
  - yarn global add greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

after_script:
  - greenkeeper-lockfile-upload

cache: yarn

env:
  global:
    secure: rBlC1rCCFT+ykI2V48rgWtJS/2aNbtfBs51Qf5n5r2iN/cy4eTqHF/U43FIEwAWRppIOMCYpUDamklNPGbCnJEpXI7q4EifM/CpU4xJNvJVHNHKZ2FrJ4fQNIB4HPk6cVlw5s/nQf/4WWqHrlCc7On3kA0ozlxedN+CihkewUf6v5VQOdlSEkBP639hjt4I5BAXnaDWFjsWdQ4XhdgKb0VsCY2jZegeOMKMKnzPcoAyizxJIjVolMGucdB4J1IlgG4hUeVRhxLIhiH/KuhxWSUMIulS1XKQzXsON4TKCcoTQC4YljCkHr6gfaZvzamEwsECa8pPuihVqt5b9IwFfFNm484Ny2lUoq4qRMP9E7lUjG0ky9azGfR+RuVfGCt2vhnO+f96VSKcaN9XUhEO6B18Yc54cOFSoRSPac553Dxa95udHr2ZLhnYAfw2yBN9oq4nc7CddX4vAS+ZnT3u+jbY7AVpfaPu2xeRnnhp8q0yEQ067OiApghKdiupZI8TGS+ebc564Xypwew1gx3N9i9+uKkNNM2Ws6V+g4Ao8u2GlpAUeBQ0ePRm4DQvlRkiS54Hb5XaedOj0yikMcl8K4I8+vTkOpW1rdovTxFDoevgZIz7imgQzcMsQ3RPsmNorwzSh9SBqG16e1BW2W5UlnAqn4XXgzktmo50b5r72Bxw=
