[context.crystal-build-system]
  command = """
    wget https://github.com/crystal-lang/crystal/releases/download/0.25.0/crystal-0.25.0-1-linux-x86_64.tar.gz && \
    tar -xzf crystal-0.25.0-1-linux-x86_64.tar.gz && \
    ./crystal-0.25.0-1/bin/crystal run src/www.cr
  """
